### ISSUE TITLE
Aurelia app doesn't mount again after being unmounted

### ISSUE THREAD

**Issue by jmezach** [peterpolman/single-spa-aurelia-framework#1]
First of all thanks @peterpolman for your work on this. I've been experimenting with this library for a bit to see if it could help us more cleanly separate our current frontend built on Aurelia. So far it seems to work perfectly for most part, but I'm facing an issue when an Aurelia single-spa app is being unmounted and then later on it is mounted again. In that scenario the `aurelia` instance seems to be attached to the old host element which has been removed from the DOM by single-spa, thus the UI doesn't appear at all. Is that a known issue?

**Comment by jmezach** [comment]
I have managed to work around the issue by explicitly setting `host` to `null` and `hostConfigured` to `false` on the `aurelia` instance in my `getInstance` method. Unfortunately `hostConfigured` isn't part of the public API so I'm not sure if this will break anything else, but so far it seems to work as a charm in my experiments.

I think this can actually be done as part of the unmount lifecycle method for single-spa. If you want I can submit a PR.

**Comment by peterpolman** [comment]
The issue you mentioned we did not encounter (yet). I'll keep an eye open for it though! Your PR is of course very welcome:) I'll try to squeeze in a quick review somewhere next week.

**Comment by jmezach** [comment]
I've created PR #2.

I was thinking it might have been related to using Single SPA's layout engine. Are you using that in your scenario as well? It looks like the layout engine actually removes the elements from the DOM after unmounting the app, so that might explain why it wasn't working in my scenario.

**Comment by peterpolman** [comment]
> I've created PR #2.

Thanks! Will test the changes against our implementation and ship it asap.

> Are you using that in your scenario as well?

Nope. We currently specify the container elements the apps are mounted into ourselves and didn't encounter a need to use the layout engine yet. Having no containers element available for single-spa to mount the app in seems like a probable cause for your issue though:)
