### ISSUE TITLE
Router not deactivated and reset on unmounting

### ISSUE THREAD

**Issue by jmezach** [peterpolman/single-spa-aurelia-framework#4]
I just ran into another issue when the Aurelia app is using Aurelia's router functionality internally. After unmounting the Aurelia app it seems that the navigation event is still being handled by the Aurelia router, which then determines that the current route is invalid (since it doesn't exist in the scope of the unmounted app) and thus tries to redirect again to the original route. Obviously when the Aurelia app is unmounted its router should no longer listen to any navigation events since it is no longer in play.

I've looked through the Aurelia code and I noticed [this piece of code](https://github.com/aurelia/framework/blob/89965047331edb39a45f266f20916f920c0dd5e7/src/aurelia.js#L120-L123) from the setRoot method on the Aurelia instance. This seems to deactivate and reset any existing router so that a new one can take its place. Interestingly this is typically done when starting an Aurelia app, and not during teardown.

I have duplicated this piece of code in the unmount lifecycle method of this module and that seems to resolve my issue. I'd be happy to submit a PR for it of course.

**Comment by peterpolman** [comment]
Follow up for this issue in https://github.com/peterpolman/single-spa-aurelia-framework/issues/7
