### ISSUE TITLE
Can this work with Aurelia 2?

### ISSUE THREAD

**Issue by cluka** [peterpolman/single-spa-aurelia-framework#8]
Hi, I'm very interested in Your work. Can it be used with Aurelia 2?
If so, can You provide some examples?

Thanks

**Comment by peterpolman** [comment]
It was initially meant to support a migration from Aurelia1 to Angular so it has never been tested within Aurelia 2. Sorry to say I don't have any examples for that, nor do I expect that it would work out of the box 😇
